{{- if and .Values.credentials.username .Values.credentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie.dbCredentialsSecretName" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.credentials.username | quote }}
  password: {{ .Values.credentials.password | quote }}
{{- end }}
