{{- $username := "" -}}
{{- $password := "" -}}
{{- $postgresPassword := "" -}}

{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) .Values.postgresql.auth.username .Values.postgresql.auth.password -}}
  {{- $username = .Values.postgresql.auth.username -}}
  {{- $password = .Values.postgresql.auth.password -}}
  {{- $postgresPassword = (.Values.postgresql.auth.postgresPassword | default .Values.postgresql.auth.password) -}}
{{- end -}}

{{- if $username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mealie.dbCredentialsSecretName" . }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ $username | quote }}
  password: {{ $password | quote }}
  postgres-password: {{ $postgresPassword | quote }}
{{- end }}
